# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='link',
            new_name='movie_kind',
        ),
    ]
