# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20161029_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='movie',
            name='play_time_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='removed_check',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fav',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='playing',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tag',
            field=models.CharField(default='', max_length=120),
        ),
    ]
