# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20161103_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
