# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20161106_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_digest',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_seek',
            field=models.CharField(default='', max_length=120),
        ),
    ]
