# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20161106_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sj',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
